# Generated by Django 3.2.7 on 2023-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0032_hamburguesas_sugerencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesas',
            name='sugerencias',
            field=models.TextField(verbose_name='sugerencias'),
        ),
    ]
