# Generated by Django 3.2.7 on 2023-07-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0033_alter_hamburguesas_sugerencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesas',
            name='sugerencias',
        ),
    ]
