# Generated by Django 3.2.7 on 2023-07-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0034_remove_hamburguesas_sugerencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesas',
            name='sugerencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
