# Generated by Django 3.2.7 on 2023-06-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20230630_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='hamburguesas',
            new_name='producto',
        ),
    ]
