# Generated by Django 3.2.7 on 2023-06-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_hamburguesas_lineapedido_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Línea Pedido', 'verbose_name_plural': 'Líneas Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='created',
            new_name='created_at',
        ),
    ]
